'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { motion, useScroll, useTransform } from 'framer-motion'
import { 
  ArrowRight,
  Rocket,
  Code2,
  Users,
  Zap,
  Shield,
  Globe2,
  Box,
  ChevronRight,
  Play,
  ExternalLink
} from 'lucide-react'
import { useWallet } from '@/hooks/useWallet'

export default function Home() {
  const { connect, address, isConnected, isConnecting } = useWallet()
  const { scrollYProgress } = useScroll()
  const y = useTransform(scrollYProgress, [0, 1], ['0%', '50%'])

  const features = [
    {
      icon: <Code2 className="w-8 h-8" />,
      title: 'Spearheading CosmWasm Innovations',
      description: 'PolyOne is at the forefront of smart contract innovation, powered by cutting-edge Polygon CDK platform.'
    },
    {
      icon: <Zap className="w-8 h-8" />,
      title: 'Token Factory',
      description: 'Real interchain tokens with native IBC support and seamless cross-chain transfers.'
    },
    {
      icon: <Users className="w-8 h-8" />,
      title: 'Built-In Social Operating System',
      description: 'Communities are the most important part of blockchain projects. Built-in DAO infrastructure for governance.'
    },
    {
      icon: <Shield className="w-8 h-8" />,
      title: '100% Community Owned',
      description: 'PolyOne grew out of the community with no VC funding, ensuring complete decentralization.'
    },
    {
      icon: <Globe2 className="w-8 h-8" />,
      title: 'Smooth Cross-Chain Interactions',
      description: 'Built on Polygon ecosystem with AggLayer integration for seamless interoperability.'
    },
    {
      icon: <Box className="w-8 h-8" />,
      title: 'Rewarding Developers',
      description: 'Developers earn a portion of gas fees generated by their contracts, making it easier to monetize.'
    }
  ]

  const apps = [
    { name: 'Chain Factory', category: 'Infrastructure', gradient: 'from-purple-500 to-pink-500' },
    { name: 'zkEVM Engine', category: 'Security', gradient: 'from-blue-500 to-cyan-500' },
    { name: 'AggLayer Bridge', category: 'Interoperability', gradient: 'from-green-500 to-emerald-500' },
    { name: 'Validator Network', category: 'Staking', gradient: 'from-orange-500 to-red-500' }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 via-purple-950/20 to-slate-950 text-white">
      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 bg-slate-950/80 backdrop-blur-xl border-b border-white/10">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 via-pink-500 to-cyan-500 flex items-center justify-center transform group-hover:scale-110 transition-transform">
              <Rocket className="w-6 h-6" />
            </div>
            <span className="text-xl font-bold bg-gradient-to-r from-purple-400 via-pink-400 to-cyan-400 bg-clip-text text-transparent">
              PolyOne Network
            </span>
          </Link>

          <div className="hidden md:flex items-center gap-8">
            <Link href="#build" className="text-gray-400 hover:text-white transition-colors">Build on PolyOne</Link>
            <Link href="#apps" className="text-gray-400 hover:text-white transition-colors">Apps</Link>
            <Link href="#ecosystem" className="text-gray-400 hover:text-white transition-colors">Ecosystem</Link>
          </div>

          <div className="flex items-center gap-4">
            {isConnected ? (
              <div className="px-4 py-2 rounded-full bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/30 text-sm font-medium">
                {address?.slice(0, 6)}...{address?.slice(-4)}
              </div>
            ) : (
              <button
                onClick={connect}
                disabled={isConnecting}
                className="px-6 py-2.5 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 font-semibold transition-all transform hover:scale-105"
              >
                {isConnecting ? 'Connecting...' : 'Connect Wallet'}
              </button>
            )}
            <Link 
              href="/dashboard"
              className="px-6 py-2.5 rounded-full border border-purple-500/50 hover:bg-purple-500/10 font-semibold transition-all"
            >
              Launch App
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-6 overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0 overflow-hidden">
          <motion.div
            className="absolute top-1/4 -left-1/4 w-96 h-96 bg-purple-500/30 rounded-full blur-3xl"
            animate={{
              scale: [1, 1.2, 1],
              opacity: [0.3, 0.5, 0.3],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute top-1/3 right-1/4 w-96 h-96 bg-pink-500/30 rounded-full blur-3xl"
            animate={{
              scale: [1.2, 1, 1.2],
              opacity: [0.3, 0.5, 0.3],
            }}
            transition={{
              duration: 10,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute bottom-1/4 left-1/3 w-96 h-96 bg-cyan-500/30 rounded-full blur-3xl"
            animate={{
              scale: [1, 1.3, 1],
              opacity: [0.2, 0.4, 0.2],
            }}
            transition={{
              duration: 12,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
        </div>

        <div className="relative max-w-6xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-6xl md:text-8xl font-bold mb-6 leading-tight">
              The Incubator of the
              <br />
              <span className="bg-gradient-to-r from-purple-400 via-pink-400 to-cyan-400 bg-clip-text text-transparent">
                Polygon Ecosystem
              </span>
            </h1>
            
            <p className="text-2xl md:text-3xl text-gray-400 mb-12 font-light">
              Smart Contracts × Community
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-16">
              <Link 
                href="/auth/signup"
                className="group px-8 py-4 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 font-semibold transition-all transform hover:scale-105 flex items-center gap-2"
              >
                Start using PolyOne
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
              <button className="group px-8 py-4 rounded-full border border-white/20 hover:bg-white/5 font-semibold transition-all flex items-center gap-2">
                <Play className="w-5 h-5" />
                Watch how it works
              </button>
            </div>

            {/* Quick Start Cards */}
            <div className="grid md:grid-cols-3 gap-6 mt-20">
              {[
                {
                  title: 'Quick Start Guide',
                  description: 'Install one of the interchain wallets that support Polygon to get started.',
                  link: '/start',
                  linkText: 'Start using PolyOne'
                },
                {
                  title: 'Build something',
                  description: 'PolyOne is an easy and fast place to build interchain projects.',
                  link: '/docs',
                  linkText: 'Start building'
                },
                {
                  title: 'Participate',
                  description: 'A DAO Network Managed by SubDAOs, Answerable to the Community.',
                  link: '/governance',
                  linkText: 'The Council'
                }
              ].map((card, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 + i * 0.1 }}
                  className="bg-gradient-to-br from-white/5 to-white/0 backdrop-blur-lg rounded-2xl p-8 border border-white/10 hover:border-purple-500/50 transition-all group"
                >
                  <h3 className="text-xl font-bold mb-4">{card.title}</h3>
                  <p className="text-gray-400 mb-6 leading-relaxed">{card.description}</p>
                  <Link 
                    href={card.link}
                    className="inline-flex items-center gap-2 text-purple-400 hover:text-purple-300 font-semibold group-hover:gap-3 transition-all"
                  >
                    {card.linkText}
                    <ArrowRight className="w-4 h-4" />
                  </Link>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* Foundation Section */}
      <section id="build" className="py-32 px-6 relative">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-20">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-5xl md:text-6xl font-bold mb-6">
                The foundation for
                <br />
                <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
                  Interchain projects
                </span>
              </h2>
              <p className="text-xl text-gray-400 max-w-3xl mx-auto">
                Native interoperability, dynamic transaction fees, community-centric growth, 
                and pioneering multi-chain smart contract deployments
              </p>
            </motion.div>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="bg-gradient-to-br from-white/5 to-white/0 backdrop-blur-lg rounded-2xl p-8 border border-white/10 hover:border-purple-500/50 transition-all group"
              >
                <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold mb-4">{feature.title}</h3>
                <p className="text-gray-400 leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Apps Section */}
      <section id="apps" className="py-32 px-6 relative">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-12">
            <h2 className="text-4xl md:text-5xl font-bold">
              <span className="bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
                Apps on PolyOne
              </span>
            </h2>
            <span className="text-gray-400">Featured by PolyOne Apps DAO</span>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {apps.map((app, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ scale: 1.05 }}
                className="relative group cursor-pointer"
              >
                <div className={`absolute inset-0 bg-gradient-to-br ${app.gradient} opacity-20 rounded-2xl blur-xl group-hover:opacity-40 transition-opacity`} />
                <div className="relative bg-gradient-to-br from-white/10 to-white/0 backdrop-blur-lg rounded-2xl p-8 border border-white/10 group-hover:border-white/30 transition-all">
                  <div className="text-xs text-gray-400 mb-2">{app.category}</div>
                  <h3 className="text-xl font-bold mb-4">{app.name}</h3>
                  <ChevronRight className="w-6 h-6 text-gray-400 group-hover:text-white group-hover:translate-x-1 transition-all" />
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Performance Features */}
      <section className="py-32 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl md:text-5xl font-bold mb-8">
                Gateway to
                <br />
                <span className="bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">
                  App Chains
                </span>
              </h2>
              <div className="space-y-6">
                {[
                  { title: 'Supercharged Performance', desc: 'Faster block times for notable developer and user experience' },
                  { title: 'DeFi & NFTs in DNA', desc: 'Built with DeFi and NFTs in mind for exciting applications' },
                  { title: 'Developer-Friendly', desc: 'Ease of development with secure coding environment' },
                  { title: 'Fast Upgrades', desc: 'Designed for fast and flexible upgrades' }
                ].map((item, i) => (
                  <div key={i} className="flex gap-4">
                    <div className="w-2 h-2 rounded-full bg-gradient-to-r from-purple-400 to-pink-400 mt-2" />
                    <div>
                      <h4 className="font-bold mb-1">{item.title}</h4>
                      <p className="text-gray-400">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-purple-500/20 to-cyan-500/20 rounded-3xl blur-3xl" />
              <div className="relative bg-gradient-to-br from-white/10 to-white/0 backdrop-blur-lg rounded-3xl p-12 border border-white/10">
                <div className="space-y-8">
                  <div className="flex items-center gap-4">
                    <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                      <Zap className="w-8 h-8" />
                    </div>
                    <div>
                      <div className="text-3xl font-bold">10,000+</div>
                      <div className="text-gray-400">Transactions/sec</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-cyan-500 to-blue-500 flex items-center justify-center">
                      <Shield className="w-8 h-8" />
                    </div>
                    <div>
                      <div className="text-3xl font-bold">99.99%</div>
                      <div className="text-gray-400">Uptime SLA</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center">
                      <Globe2 className="w-8 h-8" />
                    </div>
                    <div>
                      <div className="text-3xl font-bold">100+</div>
                      <div className="text-gray-400">Connected Chains</div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-32 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-gradient-to-br from-purple-500/10 to-pink-500/10 backdrop-blur-lg rounded-3xl p-16 border border-purple-500/20"
          >
            <h2 className="text-5xl md:text-6xl font-bold mb-8">
              Welcome home
            </h2>
            <p className="text-xl text-gray-400 mb-12 max-w-2xl mx-auto">
              Whether you're a developer, validator, or blockchain enthusiast, 
              there's room for you to contribute to PolyOne
            </p>
            <Link 
              href="/auth/signup"
              className="inline-flex items-center gap-2 px-8 py-4 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 font-semibold transition-all transform hover:scale-105"
            >
              Start Building Now
              <ArrowRight className="w-5 h-5" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 py-12 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8 mb-12">
            <div>
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                  <Rocket className="w-6 h-6" />
                </div>
                <span className="font-bold text-lg">PolyOne</span>
              </div>
              <p className="text-gray-400 text-sm">
                The Incubator of the Polygon Ecosystem
              </p>
            </div>
            
            {[
              { title: 'Build', links: ['Documentation', 'Quick Start', 'GitHub'] },
              { title: 'Use', links: ['Wallets', 'Apps', 'DEX'] },
              { title: 'Community', links: ['Discord', 'Twitter', 'Forum'] }
            ].map((section, i) => (
              <div key={i}>
                <h4 className="font-bold mb-4">{section.title}</h4>
                <ul className="space-y-2">
                  {section.links.map((link, j) => (
                    <li key={j}>
                      <Link href="#" className="text-gray-400 hover:text-white transition-colors text-sm">
                        {link}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          
          <div className="border-t border-white/10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-gray-400">
            <div>© 2025 PolyOne Network. Built for Polygon Buildathon.</div>
            <div className="flex gap-6">
              <Link href="#" className="hover:text-white transition-colors">Privacy</Link>
              <Link href="#" className="hover:text-white transition-colors">Terms</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
